---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /users/findByPrefixOfName:
    post:
      tags:
        - user-controller
      summary: "Find users by prefix of name"
      operationId: findByPrefixOfName
      requestBody:
        content:
          application/json:
            schema:
              type: string
              description: "Prefix of name"
        required: true
      responses:
        '200':
          description: "Returns list of users"
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/User"
  "/users/edit/{id}":
    post:
      tags:
        - user-controller
      operationId: editUserById
      parameters:
        - name: id

          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserForm"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/User"
  "/users/delete/{id}":
    post:
      tags:
        - user-controller
      operationId: deleteUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  "/users/create":
    post:
      tags:
        - user-controller
      operationId: addNewUser
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserForm"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/User"
  "/users/addPhone/{id}":
    post:
      tags:
        - user-controller
      operationId: addNewPhoneNumber
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PhoneRecordForm"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/PhoneRecord"
  "/phones/findByNumber":
    post:
      tags:
        - phone-record-controller
      operationId: findByNumber
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/PhoneRecord"
  "/phones/edit/{id}":
    post:
      tags:
        - phone-record-controller
      operationId: editPhoneRecord
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PhoneRecordForm"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/PhoneRecord"
  "/users":
    get:
      tags:
        - user-controller
      operationId: findAll
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/User"
  "/users/{id}":
    get:
      tags:
        - user-controller
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/User"
  "/users/getAllPhones/{id}":
    get:
      tags:
        - user-controller
      operationId: findAllPhonesByUserId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/PhoneRecord"
  "/phones":
    get:
      tags:
        - phone-record-controller
      operationId: findAll_1
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/PhoneRecord"
  "/phones/{id}":
    get:
      tags:
        - phone-record-controller
      operationId: getNumberById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/PhoneRecord"
  "/phones/delete/{id}":
    get:
      tags:
        - phone-record-controller
      operationId: deletePhoneRecord
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
components:
  schemas:
    PhoneRecord:
      required:
        - number
        - ownerName
      type: object
      properties:
        id:
          type: integer
          format: int64
        ownerName:
          type: string
        number:
          type: string
    User:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        numbers:
          type: array
          items:
            "$ref": "#/components/schemas/PhoneRecord"
    UserForm:
      required:
        - name
      type: object
      properties:
        name:
          type: string
    PhoneRecordForm:
      required:
        - number
        - ownerName
      type: object
      properties:
        ownerName:
          type: string
        number:
          type: string
